name: Testes
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: pytest
      - run: mypy
      - run: calculadora soma 2 3
name: Testes
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: pytest
      - run: mypy
      - run: calculadora soma 2 3

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t calculadora-python .
      - run: docker run --rm calculadora-python soma 2 3
      - run: docker run --rm calculadora-python converter celsius-fahrenheit 100